Mealio.WebMVC/Models/ErrorViewModel.cs
using System;

namespace Mealio.WebMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mealio.WebMVC/Controllers/HomeController.cs
using Mealio.WebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mealio.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mealio.WebMVC/Controllers/IngredientController.cs
using Mealio.Data;
using Mealio.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mealio.WebMVC.Controllers
{
    public class IngredientController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IngredientController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Ingredient (GET)
        public IActionResult Index()
        {
            var service = CreateIngredientService();
            var modelList = service.GetIngredients();
            return View(modelList);
        }

        
        // Ingredient/Edit/{id} (GET)
        // Ingredient/Edit/{id} (POST)
        // Ingredient/Delete/{id} (GET)
        // Ingredient/DeletePost/{id} (POST)

        private IngredientService CreateIngredientService()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = Guid.Parse(claim.Value);
            return new IngredientService(_context, userId);
        }
    }
}

Mealio.WebMVC/Controllers/MealController.cs
using Mealio.Data;
using Mealio.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mealio.WebMVC.Controllers
{
    public class MealController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MealController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Meal/Index (GET)


        // Meal/Details/{id} (GET)


        // Meal/Create (GET)


        // Meal/Create (POST)


        // Meal/Edit/{id} (GET)


        // Meal/Edit/{id} (POST)


        // Meal/Delete/{id} (GET)


        // Meal/DeletePost/{id} (POST)

        private MealService CreateMealServive()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = Guid.Parse(claim.Value);
            return new MealService(_context, userId);
        }
    }
}

Mealio.WebMVC/Controllers/MealIngredientController.cs
using Mealio.Data;
using Mealio.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mealio.WebMVC.Controllers
{
    public class MealIngredientController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MealIngredientController(ApplicationDbContext context)
        {
            _context = context;
        }


        // MealIngredient/Create(GET)

        
        // MealIngredient/Create(POST)
        
       
        // MealIngredient/Edit/{id} (GET)
        
        
        // MealIngredient/Edit/{id} (POST)

        private MealIngredientService CreateMealIngredientServive()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = Guid.Parse(claim.Value);
            return new MealIngredientService(_context, userId);
        }
    }
}

Mealio.WebMVC/Controllers/MealPlanController.cs
using Mealio.Data;
using Mealio.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mealio.WebMVC.Controllers
{
    public class MealPlanController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MealPlanController(ApplicationDbContext context)
        {
            _context = context;
        }

        // MealPlan/Index (GET)


        // MealPlan/Details/{id} (GET)


        // MealPlan/Create (GET)


        // MealPlan/Create (POST)


        // MealPlan/Edit/{id} (GET)


        // MealPlan/Edit/{id} (POST)


        // MealPlan/Delete/{id} (GET)


        // MealPlan/DeletePost/{id} (POST)


        private MealPlanService CreateMealPlanServive()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            var userId = Guid.Parse(claim.Value);
            return new MealPlanService(_context, userId);
        }
    }
}

Mealio.WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mealio.WebMVC/Views/Ingredient/Index.cshtml
@model IEnumerable<Mealio.Models.IngredientModels.IngredientListItem>

<div class="container pt-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Ingredient List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Ingredient" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New Ingredient
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Ingredient Name
                    </th>
                    <th>
                        Units
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="50%">@obj.Name</td>
                        <td width="30%">@obj.Units</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Ingredient" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="Ingredient" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No ingredients exist.</p>
    }
</div>

Mealio.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mealio.WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mealio.WebMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Mealio.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>